import React from 'react'

export const About = () => (
    <div>
    <h2>About</h2>
    <p>HELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELO</p>
    <p>HELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELO</p>
    <p>HELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELO</p>
    <p>HELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELO</p>
    <p>HELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELO</p>
    <p>HELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELO</p>
    <p>HELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELO</p>
    </div>
)

//export default About
