import React from 'react'

export const Home = () => (
    <div>
    <h2>Hello</h2>
    <p>HELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELO</p>
    <p>HELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELO</p>
    <p>HELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELOHELO</p>
    </div>
)


